name: expandable_text_widget
description: A new Flutter package.
version: 0.0.6
homepage: https://github.com/SunnatilloQuantic/Expandeble-Text-Widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

