name: expandable_text_widget
description: A new Flutter package. Works for iOS, Android, Web, Linux, MacOS and Windows apps
version: 0.0.7
author: Sunnatillo Shavkatov <sunnatilloshavkatov@gmail.com>
homepage: https://github.com/SunnatilloQuantic/Expandeble-Text-Widget

environment:
  sdk: ">=2.12.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

